-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 09:33:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema phonodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phonodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phonodb` DEFAULT CHARACTER SET utf8 ;
USE `phonodb` ;

-- -----------------------------------------------------
-- Table `phonodb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonodb`.`person` (
  `cpf` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `profession` VARCHAR(45) NULL,
  `requester` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `dn` VARCHAR(45) NULL,
  `fono` VARCHAR(45) NULL,
  `insurance` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phonodb`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonodb`.`exam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_cpf` INT NOT NULL,
  `laudo` VARCHAR(500) NULL,
  `monoE` VARCHAR(45) NULL,
  `dissE` VARCHAR(45) NULL,
  `dbnaE` VARCHAR(45) NULL,
  `srtE` VARCHAR(45) NULL,
  `monoD` VARCHAR(45) NULL,
  `dbnaD` VARCHAR(45) NULL,
  `srtD` VARCHAR(45) NULL,
  `pressaoE` VARCHAR(45) NULL,
  `complE` VARCHAR(45) NULL,
  `volumeE` VARCHAR(45) NULL,
  `gradE` VARCHAR(45) NULL,
  `fechaE` VARCHAR(45) NULL,
  `pressaoD` VARCHAR(45) NULL,
  `complD` VARCHAR(45) NULL,
  `volumeD` VARCHAR(45) NULL,
  `gradD` VARCHAR(45) NULL,
  `fechaD` VARCHAR(45) NULL,
  `contraLD1` VARCHAR(45) NULL,
  `contraLD2` VARCHAR(45) NULL,
  `contraLD3` VARCHAR(45) NULL,
  `contraLD4` VARCHAR(45) NULL,
  `contraLE1` VARCHAR(45) NULL,
  `contraLE2` VARCHAR(45) NULL,
  `contraLE3` VARCHAR(45) NULL,
  `contraLE4` VARCHAR(45) NULL,
  `ipsiD1` VARCHAR(45) NULL,
  `ipsiD2` VARCHAR(45) NULL,
  `ipsiD3` VARCHAR(45) NULL,
  `ipsiD4` VARCHAR(45) NULL,
  `ipsiE1` VARCHAR(45) NULL,
  `ipsiE2` VARCHAR(45) NULL,
  `ipsiE3` VARCHAR(45) NULL,
  `e1` VARCHAR(45) NULL,
  `e2` VARCHAR(45) NULL,
  `e3` VARCHAR(45) NULL,
  `e4` VARCHAR(45) NULL,
  `e5` VARCHAR(45) NULL,
  `e6` VARCHAR(45) NULL,
  `e7` VARCHAR(45) NULL,
  `e8` VARCHAR(45) NULL,
  `d1` VARCHAR(45) NULL,
  `d2` VARCHAR(45) NULL,
  `d3` VARCHAR(45) NULL,
  `d4` VARCHAR(45) NULL,
  `d5` VARCHAR(45) NULL,
  `d6` VARCHAR(45) NULL,
  `d7` VARCHAR(45) NULL,
  `d8` VARCHAR(45) NULL,
  INDEX `fk_exam_person_idx` (`person_cpf` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_exam_person`
    FOREIGN KEY (`person_cpf`)
    REFERENCES `phonodb`.`person` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
