-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 09:33:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema phonodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phonodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phonodb` DEFAULT CHARACTER SET utf8 ;
USE `phonodb` ;

-- -----------------------------------------------------
-- Table `phonodb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonodb`.`person` (
  `cpf` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `profession` VARCHAR(45) NULL,
  `requester` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `dn` VARCHAR(45) NULL,
  `fono` VARCHAR(45) NULL,
  `insurance` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phonodb`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonodb`.`exam` (
  `person_cpf` INT NOT NULL,
  `laudo` VARCHAR(500) NULL,
  `monoE` INT NULL,
  `dissE` INT NULL,
  `dbnaE` INT NULL,
  `srtE` INT NULL,
  `monoD` INT NULL,
  `dbnaD` INT NULL,
  `srtD` INT NULL,
  `pressaoE` INT NULL,
  `complE` INT NULL,
  `volumeE` INT NULL,
  `gradE` INT NULL,
  `fechaE` INT NULL,
  `pressaoD` INT NULL,
  `complD` INT NULL,
  `volumeD` INT NULL,
  `gradD` INT NULL,
  `fechaD` INT NULL,
  `contraLD1` INT NULL,
  `contraLD2` INT NULL,
  `contraLD3` INT NULL,
  `contraLD4` INT NULL,
  `contraLE1` INT NULL,
  `contraLE2` INT NULL,
  `contraLE3` INT NOT NULL,
  `contraLE4` INT NULL,
  `ipsiD1` INT NULL,
  `ipsiD2` INT NULL,
  `ipsiD3` INT NULL,
  `ipsiD4` INT NULL,
  `ipsiE1` INT NULL,
  `ipsiE2` INT NULL,
  `ipsiE3` INT NULL,
  `e1` VARCHAR(45) NULL,
  `e2` INT NULL,
  `e3` INT NULL,
  `e4` INT NULL,
  `e5` INT NULL,
  `e6` INT NULL,
  `e7` INT NULL,
  `e8` INT NULL,
  `d1` INT NULL,
  `d2` INT NULL,
  `d3` INT NULL,
  `d4` INT NULL,
  `d5` INT NULL,
  `d6` INT NULL,
  `d7` INT NULL,
  `d8` INT NULL,
  INDEX `fk_exam_person_idx` (`person_cpf` ASC) VISIBLE,
  PRIMARY KEY (`person_cpf`),
  CONSTRAINT `fk_exam_person`
    FOREIGN KEY (`person_cpf`)
    REFERENCES `phonodb`.`person` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
