export const proficioes = [
  "Aposentado (a)",
  "Advogado (a)",
  "Aux. De Serviços Gerais",
  "Do lar",
  "Eng. Civil",
  "Eng. Mecânico",
  "Estudante",
  "Fisioterapeuta",
  "Fonoaudiólogo (a)",
  "Aux. De Serviços Gerais",
  "Médico (a)",
  "Mecänico",
  "Professor (a)",
  "Psicólogo (a)",
  "Rep. Comercial",
  "Costureira",
  "Op. de empilhadeira",
  "Auxiliar de Escritorio",
  "Inspetor de qualidade",
  "Encarregado de Caldeiraria",
  "Eletricista",
  "Serralheiro",
  "Auxiliar administrativo",
  "Lavrador",
  " Analista Comercial",
  "Comerciante",
  "Vidraceiro",
  "Técnico em Contabilidade",
  "Motoboy",
  "Bancário (a)",
  "Auxiliar de Produção",
  "Diarista",
  "Projetista Mecânico",
  "Músico",
  "Carreteiro (a)",
  "Controlador(a) de qualidade",
  "Pedreiro",
  "Balconista",
  "Op. De Processos Industriais",
];
