export const solicitantes = [
  "Dr. Vinícius Malaquias Ramos",
  "Dr. Daniel Pains Nogueira",
  "Dra. Ligia Arantes Abreu Neves",
  "Dr. Sebastião Tadeu Cordeiro",
  "Dr. Felipe Medeiros Pinheiro",
  "Dra. Priscilla Delasalle Ribeiro",
  "Dra. Juliana Arruda Silveira Wardini",
  "Dr. Luiz Fernando Campos de Andrade",
  "Dr. Braulio Lima Cruz Rocha",
  "Dr. João Penna Martins Vieira",
  "Dra. Isneli Maquart de Oliveira",
  "Dra. Aurélia Albuquerque Martins",
  "Dra. Bárbara Cecilia B. Moreira	",
  "Dra. Karine  V. G. de Oliveira	",
  "Dra. Lorrane Caroline Braga Rodrigues",
  "Dr. Fábio da Cunha Peixoto Ladeira",
  "Dra. Denise da Matta Navarro",
  "Dr. Alessandro Fernandes Guimarães",
  "Dra. Camila Isabela Ribeiro Vieira",
  "Dra. Rubiana Ferreira Sousa A. Lima",
  "Dra. Gabriela Penha Alves",
  "Dra. Anna Paula B. de A. Pires",
];
